# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy necessary files for dependency installation and build
COPY package*.json tsconfig.json ./
COPY src ./src
COPY README.md ./
COPY README.zh-CN.md ./

# Install dependencies (including dev dependencies needed for building)
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Expose docs directory if needed (optional)

# Command to run the MCP server
CMD ["node", "build/index.js", "--docsDir", "./docs"]
